import { useEffect, useMemo, useState } from 'react'
import emailjs from '@emailjs/browser'
import { createClient } from '@supabase/supabase-js'
import { Link } from 'react-router-dom'

const supabase = createClient(import.meta.env.VITE_SUPABASE_URL, import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY)
const projects = [
  { id: 'rescuebite', title: 'RescueBite', subtitle: 'AI-powered food distribution', tags: ['AI/ML', 'React'], img: '/rescuebite.png' },
  { id: 'triplens', title: 'TripLens', subtitle: 'Trip planner + expense tracker', tags: ['React Native', 'PWA'], img: '/triplens.png' },
  { id: 'cardiacsyncai', title: 'Cardiac Sync AI', subtitle: 'AI-powered cardiac monitoring', tags: ['Healthcare', 'Real-time'], img: '/card.jpeg' },
  { id: 'nephronx', title: 'NephronX', subtitle: 'AI-driven kidney health platform', tags: ['Healthcare', 'Predictive'], img: '/Neph.jpg' },
  { id: 'hyderabadengineeringworks', title: 'Hyderabad Engineering Works', subtitle: 'Industrial engineering website', tags: ['React', 'Corporate'], img: '/hyde.png' },
]
const services = [
  ['01', 'Website Development', 'Fast, pixel-precise sites on modern stacks. No templates, pure craft.'], ['02', 'Web Hosting', '99.9% uptime SLA, edge delivery, auto-scaling, SSL-secured.'], ['03', 'Debugging & QA', 'Diagnostics on bottlenecks and race conditions - traced and fixed.'], ['04', 'Google SEO', 'Search-focused optimization for visibility and organic traffic.'], ['05', 'Customised ERP', 'Business systems that streamline operations, with integrated POS.'], ['06', 'Digital Marketing', 'Data-driven strategies that reach the right audience.'],
]
const contacts = [['General', 'Info@Xenosysweb.com'], ['Sales', 'sales@Xenosysweb.com'], ['Careers', 'hr@Xenosysweb.com'], ['Finance', 'Finance@Xenosysweb.com'], ['Procurement', 'Procurement@Xenosysweb.com'], ['Marketing', 'Marketing@Xenosysweb.com']]

function Header() {
  const [open, setOpen] = useState(false)
  const links = [['Services', '#services'], ['Work', '#work'], ['About', '#about'], ['Reviews', '#reviews']]
  return <><header className="site-header"><Link to="/" className="brand"><img src="/logo.png" alt="Xenosys Solutions" /></Link><nav className="desktop-nav">{links.map(([label, href]) => <a key={label} href={href}>{label}</a>)}<a className="nav-cta" href="#contact">Start a project</a></nav><button className="menu-toggle" onClick={() => setOpen(!open)} aria-label="Menu"><span /><span /><span /></button></header><div className={`mobile-menu ${open ? 'open' : ''}`}>{[...links, ['Contact', '#contact']].map(([label, href]) => <a key={label} href={href} onClick={() => setOpen(false)}>{label}</a>)}</div></>
}
function Hero() { return <section className="reference-hero" id="top"><div className="hero-wireframe"><div className="wire-ring wire-ring-one" /><div className="wire-ring wire-ring-two" /><div className="wire-core" /></div><div className="wrap hero-copy"><p className="eyebrow">Xenosys Solutions - web design &amp; engineering</p><h1>We design<br /><em>the web</em></h1><p className="lede">A small studio building fast, considered websites, hosting and business software - for founders, nonprofits and teams who care how it looks and how it runs.</p><div className="hero-actions"><a className="button-solid" href="#work">See our work</a><a className="button-line" href="#contact">Start a project</a></div></div><div className="scroll-cue"><i />Scroll</div></section> }
function Marquee() { const words = ['Web Development', 'Hosting', 'Debugging & QA', 'SEO', 'Custom ERP', 'Digital Marketing']; return <div className="marquee"><div>{[...words, ...words].map((word, i) => <span key={`${word}-${i}`}>{word}</span>)}</div></div> }
function SectionTitle({ eyebrow, title, copy }: { eyebrow?: string; title: string; copy?: string }) { return <div className="section-title">{eyebrow && <p className="eyebrow">{eyebrow}</p>}<h2>{title}</h2>{copy && <p>{copy}</p>}</div> }
function Services() { return <section className="reference-panel panel-services" id="services"><div className="wrap"><SectionTitle title="What we do" copy="Six services, one team end to end." /><div className="service-grid">{services.map(([num, title, copy]) => <article className="service-card" key={num}><span>{num}</span><h3>{title}</h3><p>{copy}</p></article>)}</div></div></section> }
function Work({ onOpen }: { onOpen: (id: string) => void }) { return <section className="reference-panel panel-work" id="work"><div className="wrap"><SectionTitle title="Selected work" copy="A few projects we've shipped recently, across healthcare, logistics and industry." /><div className="work-grid">{projects.map(project => <article className="work-card" key={project.id}><button onClick={() => onOpen(project.id)}><div className="project-image"><img src={project.img} alt={project.title} /></div><h3>{project.title}</h3><p>{project.subtitle}</p><div className="tags">{project.tags.map(tag => <span key={tag}>{tag}</span>)}</div></button></article>)}</div></div></section> }
function Process() { const steps = [['01', 'Discovery', 'We map your goals, audience and constraints. No assumptions.'], ['02', 'Design', 'Wireframes through to high-fidelity prototypes, reviewed together.'], ['03', 'Build', 'Modular, tested, documented code shipped in sprints.'], ['04', 'Launch', 'Staged deployment, a performance audit and monitoring.']]; return <section className="reference-panel panel-process"><div className="wrap"><SectionTitle title="How we work" /><div className="process-grid">{steps.map(([num, title, copy]) => <article key={num}><span>{num}</span><h3>{title}</h3><p>{copy}</p></article>)}</div></div></section> }
function About() { return <section className="reference-panel panel-about" id="about"><div className="wrap about-layout"><div><SectionTitle eyebrow="About Xenosys Solutions" title="Small team. Real ownership." /><p>Built on the belief that exceptional software should be accessible - not just to enterprises with big budgets, but to founders, nonprofits and ambitious teams building things that matter.</p><p>We move fast, write clean code and stay focused on outcomes. Every project gets our full attention.</p><div className="tags about-tags">{['Fast delivery', 'Clean code', 'Full ownership', 'Post-launch support'].map(tag => <span key={tag}>{tag}</span>)}</div></div><div className="about-panel">{[['Stack', 'TypeScript, React, Node.js'], ['Infra', 'AWS, edge CDN'], ['Response time', 'Within 24 hours'], ['Engagement', 'Project or retainer']].map(([key, value]) => <div key={key}><span>{key}</span><strong>{value}</strong></div>)}</div></div></section> }
type Review = { id: string; name: string; rating: number; text: string; created_at: string }
function Stars({ value }: { value: number }) { return <span className="stars" aria-label={`${value} out of 5 stars`}>{[1, 2, 3, 4, 5].map(star => <span key={star}>{star <= value ? '★' : '☆'}</span>)}</span> }
function Reviews() { const [reviews, setReviews] = useState<Review[]>([]); const [name, setName] = useState(''); const [text, setText] = useState(''); const [rating, setRating] = useState(5); const [sent, setSent] = useState(false); useEffect(() => { supabase.from('customer_reviews').select('id, name, rating, text, created_at').order('created_at', { ascending: false }).then(({ data }) => setReviews((data ?? []) as Review[])) }, []); const average = useMemo(() => reviews.length ? reviews.reduce((sum, review) => sum + review.rating, 0) / reviews.length : 0, [reviews]); async function submit(event: React.FormEvent) { event.preventDefault(); if (!name.trim() || !text.trim()) return; const { error } = await supabase.from('customer_reviews').insert({ name: name.trim(), rating, text: text.trim() }); if (!error) { setName(''); setText(''); setRating(5); setSent(true); const { data } = await supabase.from('customer_reviews').select('id, name, rating, text, created_at').order('created_at', { ascending: false }); setReviews((data ?? []) as Review[]); window.setTimeout(() => setSent(false), 3500) } } return <section className="reference-panel panel-reviews" id="reviews"><div className="wrap"><SectionTitle title="What clients say" /><div className="reviews-layout"><div className="review-form"><div className="score"><strong>{average.toFixed(1)}</strong><div><Stars value={Math.round(average)} /><small>{reviews.length} {reviews.length === 1 ? 'review' : 'reviews'}</small></div></div><hr /><h3>Leave a review</h3>{sent ? <p>Review submitted. Thank you for your feedback.</p> : <form onSubmit={submit}><input value={name} onChange={e => setName(e.target.value)} placeholder="Your name" required /><div className="rating-input"><label>Rating</label>{[1, 2, 3, 4, 5].map(value => <button type="button" key={value} onClick={() => setRating(value)} className={value <= rating ? 'selected' : ''}>★</button>)}</div><textarea value={text} onChange={e => setText(e.target.value)} placeholder="Tell us about your experience..." required /><button className="button-solid" type="submit">Submit review</button></form>}</div><div className="review-list">{reviews.length ? reviews.map(review => <article key={review.id}><div><h4>{review.name}</h4><small>{new Date(review.created_at).toLocaleDateString()}</small></div><Stars value={review.rating} /><p>“{review.text}”</p></article>) : <p>No reviews yet. Be the first to leave one.</p>}</div></div></div></section> }
function Contact() { const [form, setForm] = useState({ name: '', email: '', project: '', message: '' }); const [sent, setSent] = useState(false); async function submit(event: React.FormEvent) { event.preventDefault(); await emailjs.send(import.meta.env.VITE_EMAILJS_SERVICE_ID, import.meta.env.VITE_EMAILJS_TEMPLATE_ID, form, { publicKey: import.meta.env.VITE_EMAILJS_PUBLIC_KEY }); setForm({ name: '', email: '', project: '', message: '' }); setSent(true); window.setTimeout(() => setSent(false), 4000) } return <section className="reference-panel panel-contact" id="contact"><div className="wrap"><SectionTitle eyebrow="Let's work together" title="Start a project" copy="Tell us what you're building. We'll respond within 24 hours." /><div className="contact-layout"><div className="contact-list">{contacts.map(([label, email]) => <div key={email}><small>{label}</small><a href={`mailto:${email}`}>{email}</a></div>)}</div><div className="contact-form">{sent ? <div className="success-message"><h3>Message sent.</h3><p>We'll be in touch within 24 hours.</p></div> : <form onSubmit={submit}><div className="form-row"><label>Name<input value={form.name} onChange={e => setForm({ ...form, name: e.target.value })} placeholder="Alex Chen" required /></label><label>Email<input type="email" value={form.email} onChange={e => setForm({ ...form, email: e.target.value })} placeholder="alex@company.com" required /></label></div><label>Project type<select value={form.project} onChange={e => setForm({ ...form, project: e.target.value })} required><option value="">Select a service</option><option>Website Development</option><option>Web Hosting</option><option>Debugging & QA</option><option>Full package</option></select></label><label>Message<textarea value={form.message} onChange={e => setForm({ ...form, message: e.target.value })} placeholder="Tell us about your project, timeline and goals..." rows={5} required /></label><button className="button-solid" type="submit">Send message</button></form>}</div></div></div></section> }
function Footer() { return <footer><div className="wrap footer-row"><span>© 2026 Xenosys Solutions</span><div>{[['Services', '#services'], ['Work', '#work'], ['About', '#about'], ['Contact', '#contact']].map(([label, href]) => <a key={label} href={href}>{label}</a>)}<Link to="/privacy-policy">Privacy Policy</Link><Link to="/terms">Terms &amp; Conditions</Link></div></div></footer> }
export default function Home() { const [activeProject, setActiveProject] = useState<string | null>(null); const selected = projects.find(project => project.id === activeProject); return <div className="reference-site"><Header /><main><Hero /><Marquee /><Services /><Work onOpen={setActiveProject} /><Process /><About /><Reviews /><Contact /></main><Footer />{selected && <div className="case-study-layer" onClick={() => setActiveProject(null)}><div className="case-study" onClick={event => event.stopPropagation()}><button onClick={() => setActiveProject(null)} aria-label="Close">×</button><img src={selected.img} alt={selected.title} /><h2>{selected.title}</h2><p>Explore the thinking, design and engineering behind this project.</p></div></div>}</div> }
